In [1]:
import numpy as np

In [2]:
list = [1,2,3,4,5]
print(list)

[1, 2, 3, 4, 5]


In [1]:
print('1D Array')
a = np.array([1,2,3,4,5])
print(a)

1D Array


NameError: name 'np' is not defined

In [4]:
print('2D Array')
b = np.array([[1,2,3,4,5],
              [6,7,8,9,10]])
print(b)

2D Array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [8]:
print('3D Array')
c = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15]])
print(c)

3D Array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [9]:
print(a.size)
print(b.size)
print(c.size)

5
10
15


In [10]:
print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(2, 5)
(3, 5)


In [11]:
d = np.array([[1,2,3,4.3,5],
              [6,7,8,9.9,10],
              [11,12,13,14,15]])
print(d.dtype)

float64


In [ ]:
# Transpose matrix
# addition of 2 1D matrix