In [1]:
import numpy as np

In [2]:
x = np.ones((6),dtype=int)
x

array([1, 1, 1, 1, 1, 1])

In [3]:
z = np.zeros((4,8),dtype=int)
z

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [10]:
a = np.arange(1,21,2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [11]:
a = a.reshape(2,5)
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [ ]:
# # Task 1
# a = 1,18
# b = 20,38
# a+b
# reshape(6,3)

In [12]:
!pip install pandas

  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/29/d4/1244ab8edf173a10fd601f7e13b9566c1b525c4f365d6bee918e68381889/pandas-2.2.3-cp312-cp312-win_amd64.whl.metadata
  Obtaining dependency information for pytz>=2020.1 from https://files.pythonhosted.org/packages/11/c3/005fcca25ce078d2cc29fd559379817424e94885510568bc1bc53d7d5846/pytz-2024.2-py2.py3-none-any.whl.metadata
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB 162.5 kB/s eta 0:01:11
   ---------------------------------------- 0.1/11.5 MB 1.0 MB/s eta 0:00:12
   ---------------------------------------- 0.1/11.5 MB 1.0 MB/s eta 0:00:12
    --------------------------------------- 0.2/11.5 MB 908.0 kB/s eta 0:00:13
    --------------------------------------- 0.2/11.5 MB 919.0 kB/s eta 0:00:13
    --------------------------------------- 0.3/11.5 MB 8


[notice] A new release of pip is available: 23.2.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [13]:
import pandas as pd

In [14]:
pd.DataFrame({'Yes':[50,21],'No':[131,2]})

Yes   No
0   50  131
1   21    2

In [15]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64